name: Publish
run-name: ${{ github.actor }} is publishing a new version
on: workflow_dispatch
permissions:
  contents: write
  packages: write
  id-token: write
  pages: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          npm ci
          npm audit --omit=dev
          npm test
          npm run webpack

          npm run standard-version

          npm publish
          git push --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
      - uses: actions/deploy-pages@v2
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ secrets.ITCH_CHANNEL }}
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: dist